### ISSUE TITLE
공부시간 추가에 대한 버그

### ISSUE THREAD

**Issue by JunHyeong-99** [new3seagull/SeagullsRoom#21]
## 문제

studyDay가 같은 공부시간을 사용자가 여러 번 추가하게 된다면 사용자가 여러 개의 같은 날 공부시간을 가지게 된다.
이 문제로 인해 top10 조회, 이번 달 공부시간 조회, 오늘 공부시간 조회할 때 하나의 값을 기대하고 로직을 작성된 로직이지만 여러 개의 칼럼이 조회되어 에러가 발생한다.

## 버그 맥락
 버그가 발생한 맥락 또는 재현하기까지 절차, 또는 에러 로그
1. 사용자가 공부기록 추가를 같은 날에 여러 번 한다.
2. top10을 조회한다.
3. 동일한 사용자가 중복해서 조회된다. (top10은 한 사람은 한 번만 조회되어야 한다.
4. 또는 이번 달 공부시간 조회시 여러 개의 칼럼이 조회되어 에러가 발생한다.

## 생각할 점

같은 날 사용자의 공부시간을 어떻게 저장할 것인지??
1. 공부 시간 추가했을 때 기존의 공부 시간에 추가 될 공부시간을 더한다.
2. 총 공부시간을 기록하는 테이블을 하나 더 만든다.

**Comment by J-1ac** [comment]
1. 새로운 DB 테이블 생성:
- 장점: 기존 데이터 구조를 유지하면서 새로운 요구사항을 충족할 수 있음.
- 단점: 데이터 중복이 발생하고, 두 테이블 간 동기화 문제가 생길 수 있음.
2. 공부 기록 삽입 시 기존 row에 시간 추가:
- 장점: 데이터 중복을 줄이고 조회가 간단해짐.
- 단점: 개별 세션 정보가 손실되며, 동시성 문제가 발생할 수 있음.
3. 조회 시 SELECT 쿼리로 데이터 집계:
- 장점: 기존 데이터 구조를 변경하지 않고 요구사항을 충족할 수 있음.
- 단점: 데이터가 많아질수록 쿼리 성능이 저하될 수 있음.

**Comment by J-1ac** [comment]
SELECT 
    *
FROM 
    study
WHERE 
    study_date BETWEEN '2024-07-21 00:00:00' AND '2024-07-21 23:59:59'
GROUP BY 
    user_id, DATE(study_date);

**Comment by J-1ac** [comment]
3번으로 채택

**Comment by JunHyeong-99** [comment]
수정해야함
