### ISSUE TITLE
설정 정보 git secrete 요청

### ISSUE THREAD

**Issue by JunHyeong-99** [new3seagull/SeagullsRoom#23]
## 설명

현재 yml 파일에 jwt, openai key 등 유출되면 안되는 값들이 github에 올라간다. 
이를 git secrete를 사용해 유출에 보호하도록 해야한다.

이 후 AWS설정 파일도 유출 보호를 위해 꼭 필요해 보인다.

**Comment by J-1ac** [comment]
git ignore 추가함
